// Generates supabase/seed.sql from src/lib/seed.ts  →  node scripts/gen-seed.mjs
import ts from 'typescript'; import fs from 'fs';
const src = fs.readFileSync('src/lib/seed.ts', 'utf8');
const js = ts.transpileModule(src, { compilerOptions: { module: ts.ModuleKind.ES2020, target: ts.ScriptTarget.ES2020 } }).outputText;
const { products, concerns, categories } = await import('data:text/javascript;base64,' + Buffer.from(js).toString('base64'));
const q = v => v == null ? 'null' : `'${String(v).replace(/'/g, "''")}'`;
const arr = a => `array[${a.map(q).join(',')}]::text[]`;
let out = '-- Generated by scripts/gen-seed.mjs. Placeholder prices/copy; replace with approved catalogue.\n';
out += `insert into settings(key,value) values ('store','{"free_shipping_min":999,"announcement":["Free shipping on orders above ₹999","10% off your first order with code WELCOME10","100% pure essential oils · GC-MS tested","Made in India"]}') on conflict (key) do update set value = excluded.value;\n`;
out += `insert into coupons(code,kind,value,min_cart) values ('WELCOME10','percent',10,0) on conflict do nothing;\n`;
categories.forEach((c, i) => out += `insert into categories(slug,name,intro,sort) values (${q(c.slug)},${q(c.name)},${q(c.intro)},${i}) on conflict (slug) do nothing;\n`);
concerns.forEach((c, i) => out += `insert into concerns(slug,name,intro,color,sort) values (${q(c.slug)},${q(c.name)},${q(c.intro)},${q(c.color)},${i}) on conflict (slug) do nothing;\n`);
for (const p of products) {
  out += `with np as (insert into products(slug,name,botanical_name,tagline,description,category_id,aroma,extraction,origin,uses,suggested_blends,safety,purity,color,is_bestseller,is_new,rating,review_count,seo_title,seo_description)
  values (${q(p.slug)},${q(p.name)},${q(p.botanical_name)},${q(p.tagline)},${q(p.description)},(select id from categories where slug=${q(p.category)}),${q(p.aroma)},${q(p.extraction)},${q(p.origin)},${arr(p.uses)},${arr(p.suggested_blends)},${q(p.safety)},${q(p.purity)},${q(p.color)},${p.is_bestseller},${p.is_new},${p.rating},${p.review_count},${q(p.seo_title)},${q(p.seo_description)}) returning id),
  pc as (insert into product_concerns select np.id, c.id from np, concerns c where c.slug = any(${arr(p.concerns)}))
  insert into variants(product_id,sku,label,price,compare_at,stock,low_stock_threshold,sort) values\n  `;
  out += p.variants.map((v, j) => `((select id from np),${q(v.sku)},${q(v.label)},${v.price},${v.compare_at},${v.stock},${v.low_stock_threshold},${j})`).join(',\n  ') + ';\n';
}
out += `insert into stock_movements(variant_id,change,balance,reason,note) select id, stock, stock, 'initial', 'Opening stock' from variants;\n`;
fs.writeFileSync('supabase/seed.sql', out);
console.log('seed.sql written:', products.length, 'products');
